### ISSUE TITLE
Want some help?

### ISSUE THREAD

**Issue by br0p0p** [klaussinani/arare#1]
Saw you began working on this and got excited.

If you're open to contributions at this point, I'd love to help – testing and/or documentation to start.

**Comment by klauscfhq** [comment]
Of course! Everyone is super welcome! Currently, the main goals are to improve the documentation, support TypeScript definitions, include unit-tests & add more functions. Also, thank you a lot for taking the time to contribute : )

**Comment by br0p0p** [comment]
No problem! Might be helpful to have a "Goals" issue or something to contain functions to implement and other TODOs.
